### ISSUE TITLE
petkit purabot max pro issue

### ISSUE THREAD

**Issue by kiloptero** [Jezza34000/homeassistant_petkit#14]
### System Health details

This error originated from a custom integration.

Logger: custom_components.petkit
Source: helpers/update_coordinator.py:379
integration: Petkit Smart Devices (documentation, issues)
First occurred: 11:44:30 PM (16 occurrences)
Last logged: 11:54:21 PM

Unexpected error fetching petkit data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petkit/coordinator.py", line 47, in _async_update_data
    await self.config_entry.runtime_data.client.get_devices_data()
  File "/usr/local/lib/python3.13/site-packages/pypetkitapi/client.py", line 244, in get_devices_data
    await asyncio.gather(*record_tasks)
  File "/usr/local/lib/python3.13/site-packages/pypetkitapi/client.py", line 279, in _fetch_device_data
    endpoint = data_class.get_endpoint(device_type)
  File "/usr/local/lib/python3.13/site-packages/pypetkitapi/litter_container.py", line 247, in get_endpoint
    raise ValueError(f"Invalid device type: {device_type}")
ValueError: Invalid device type: t5

### Integration version ?

1.3.7

### In which region is your Petkit application registered?

us

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Jezaa34000/homeassistant_petkit/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

after integration try to accesa without luck
issue at when try to log on
![IMG_3572](https://github.com/user-attachments/assets/f3d029a6-eeec-42e1-8cc5-f1787f68aa37)

### Reproduction steps

install
and then try to log without luck

### Debug logs

```text
This error originated from a custom integration.

Logger: custom_components.petkit
Source: helpers/update_coordinator.py:379
integration: Petkit Smart Devices (documentation, issues)
First occurred: 11:44:30 PM (16 occurrences)
Last logged: 11:54:21 PM

Unexpected error fetching petkit data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/petkit/coordinator.py", line 47, in _async_update_data
    await self.config_entry.runtime_data.client.get_devices_data()
  File "/usr/local/lib/python3.13/site-packages/pypetkitapi/client.py", line 244, in get_devices_data
    await asyncio.gather(*record_tasks)
  File "/usr/local/lib/python3.13/site-packages/pypetkitapi/client.py", line 279, in _fetch_device_data
    endpoint = data_class.get_endpoint(device_type)
  File "/usr/local/lib/python3.13/site-packages/pypetkitapi/litter_container.py", line 247, in get_endpoint
    raise ValueError(f"Invalid device type: {device_type}")
ValueError: Invalid device type: t5
```

**Comment by Jezza34000** [comment]
Hi @kiloptero 
It's beacause i never had chance to try my integration with this new litter :-)
Can you send me a message on discord ? I will ask you to send me a link to temporary join your familiy and i will fix the Purobot MAX pro support for you :-)

**Comment by Jezza34000** [comment]
This version fix the issue : https://github.com/Jezza34000/homeassistant_petkit/releases/tag/1.3.8
